-- id is GENERATED BY DEFAULT (not ALWAYS) AS IDENTITY - unlike every other table's PK
-- (plain GENERATED ALWAYS), tests seed users with an explicit, predictable id via a raw
-- INSERT (see e.g. tests/test_db_connection.py) for readability, which GENERATED ALWAYS
-- would reject outright without an explicit OVERRIDING SYSTEM VALUE clause on every one
-- of those inserts.
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);
