ALTER TABLE users ADD COLUMN show_currently_reading INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN show_favorite INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN show_library INTEGER NOT NULL DEFAULT 1;
